    var nameData = {
	"DZA": "Algeria",
	"AGO": "Angola",
	"BEN": "Benin",
	"BFA": "Burkina Faso",
	"BDI": "Burundi",
	"BWA": "Botswana",
	"CMR": "Cameroon",
	"CPV": "Cabo Verde",
	"CAF": "Central African Republic",
	"TCD": "Chad",
	"CIV": "Côte d'Ivoire",
	"COD": "Democratic Republic of Congo",
	"DJI": "Djibouti",
	"EGY": "Egypt",
	"GNQ": "Equatorial Guinea",
	"ERI": "Eritrea",
	"ETH": "Ethiopia",
	"GAB": "Gabon",
	"GMB": "The Gambia",
	"GHA": "Ghana",
	"GIN": "Guinea",
	"GNB": "Guinea-Bissau",
	"KEN": "Kenya",
	"LSO": "Lesotho",
	"LBY": "Libya",
	"LBR": "Liberia",
	"MDG": "Madagascar",
	"MWI": "Malawi",
	"MLI": "Mali",
	"MRT": "Mauritania",
	"MUS": "Mauritius",
	"MAR": "Morocco",
	"MOZ": "Mozambique",
	"NAM": "Namibia",
	"NER": "Niger",
	"NGA": "Nigeria",
	"COG": "Republic of Congo",
	"RWA": "Rwanda",
	"SEN": "Senegal",
	"SYC": "Seychelles",
	"SLE": "Sierra Leone",
	"SOM": "Somalia",
	"ZAF": "South Africa",
	"SSD": "South Sudan",
	"SDN": "Sudan",
	"TZA": "Tanzania",
	"TGO": "Togo",
	"TUN": "Tunisia",
	"UGA": "Uganda",
	"ZMB": "Zambia",
	"ZWE": "Zimbabwe"
    }